apiVersion: v1
kind: Service
metadata:
  name: httpserver-service
  namespace: httpserver-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: httpserver